
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */

uib_view_context* uib_view_view1_create(Evas_Object* parent, void* create_callback_param) {
	elm_win_indicator_mode_set(get_window(parent), ELM_WIN_INDICATOR_SHOW);
	uib_view1_view_context* vc = calloc(1, sizeof(uib_view1_view_context));
	vc->parent = parent;
	vc->view_name = "view1";
	if (!vc->grid0) {
		vc->grid0= elm_grid_add(parent);
		vc->root_container = vc->grid0;
	}
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	uib_views_get_instance()->set_targeted_view(vc->view_name);

	//bind event handler


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);

	return (uib_view_context*)vc;
}
void uib_view1_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view1_view_context* vc = (uib_view1_view_context*)uib_app_manager->find_view_context("view1");
	if(vc->grid0) {
		elm_grid_clear(vc->grid0, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid0, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid0, 1.0, 1.0);		elm_grid_size_set(vc->grid0, 1000, 1000);
		if (!vc->bg0) {
			vc->bg0 = elm_bg_add(vc->grid0);
		}
		if(vc->bg0) {
			evas_object_size_hint_align_set(vc->bg0, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->bg0, 1.0, 1.0);			elm_bg_option_set(vc->bg0, (Elm_Bg_Option)ELM_BG_OPTION_SCALE);
			evas_object_show(vc->bg0);
		}
		if (!vc->button0) {
			vc->button0 = elm_button_add(vc->grid0);
		}
		if (vc->button0) {
			evas_object_size_hint_align_set(vc->button0, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->button0, 1.0, 1.0);			elm_object_text_set(vc->button0,_UIB_LOCALE("Button"));
			elm_object_style_set(vc->button0,"default");
			evas_object_show(vc->button0);
		}
		if (!vc->button1) {
			vc->button1 = elm_button_add(vc->grid0);
		}
		if (vc->button1) {
			evas_object_size_hint_align_set(vc->button1, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->button1, 1.0, 1.0);			elm_object_text_set(vc->button1,_UIB_LOCALE("Button"));
			elm_object_style_set(vc->button1,"default");
			evas_object_show(vc->button1);
		}
		vc->progressbar0= elm_progressbar_add(vc->grid0);
		if (vc->progressbar0) {
			evas_object_size_hint_align_set(vc->progressbar0, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->progressbar0, 1.0, 1.0);			elm_object_style_set(vc->progressbar0,"default");
			elm_progressbar_horizontal_set(vc->progressbar0, EINA_TRUE);
			elm_progressbar_value_set(vc->progressbar0,0.5);
			elm_progressbar_span_size_set(vc->progressbar0,0);
			elm_progressbar_inverted_set(vc->progressbar0, EINA_FALSE);
			evas_object_show(vc->progressbar0);
		}
		if (!vc->label0) {
			vc->label0 = elm_label_add(vc->grid0);
		}
		if(vc->label0) {
			evas_object_size_hint_align_set(vc->label0, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label0, 1.0, 1.0);			elm_object_text_set(vc->label0,_UIB_LOCALE("Label"));
			elm_label_line_wrap_set(vc->label0, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label0,0);
			elm_label_ellipsis_set(vc->label0, EINA_FALSE);
			evas_object_show(vc->label0);
		}
		if (!vc->image0) {
			vc->image0 = elm_image_add(vc->grid0);
		}
		if(vc->image0) {
			char *resource_path = NULL;
			uib_util_rm_get_resource_path(APP_RESOURCE_TYPE_IMAGE, "tmelm.png", &resource_path);
			elm_image_file_set(vc->image0, resource_path, NULL);
			if(resource_path) {
				free(resource_path);
			}
			elm_image_smooth_set(vc->image0, EINA_TRUE);
			elm_image_no_scale_set(vc->image0, EINA_FALSE);
			elm_image_resizable_set(vc->image0, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->image0, EINA_FALSE);
			elm_image_fill_outside_set(vc->image0, EINA_FALSE);
			elm_image_editable_set(vc->image0, EINA_FALSE);
			evas_object_size_hint_align_set(vc->image0, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->image0, 1.0, 1.0);
			evas_object_show(vc->image0);
		}
		elm_grid_pack(vc->grid0, vc->bg0, 0, 0, 1000, 1000);		elm_grid_pack(vc->grid0, vc->button0, 70, 777, 414, 183);		elm_grid_pack(vc->grid0, vc->button1, 521, 775, 414, 183);		elm_grid_pack(vc->grid0, vc->progressbar0, 72, 654, 864, 76);		elm_grid_pack(vc->grid0, vc->label0, 286, 223, 139, 24);		elm_grid_pack(vc->grid0, vc->image0, 0, -1, 1001, 81);		evas_object_show(vc->grid0);
	}
}

